BEGIN;

-- Local/early-environment editorial seed. Production teams can replace these
-- rows through the reviewed CMS workflow without changing route code.
INSERT INTO public_site_content (slug, kicker, title, intro, sections, publishing_state)
VALUES
  ('about', 'About INSIPS', 'Make social-impact work easier to understand.', 'INSIPS connects public discovery, contribution, evidence preparation, and independent review without flattening a nuanced organization into one score.', $$[{"title":"The product thesis","body":"Organizations should prepare evidence once and communicate reviewed facts with clear scope, meaning, and date."},{"title":"Responsible assistance","body":"Automation may prepare work, but people remain responsible for claims, review, and publication."}]$$::jsonb, 'PUBLISHED'),
  ('for-organizations', 'For organizations', 'Prepare evidence once. Stay in control of every fact.', 'A clear workspace for evidence readiness, human confirmation, transparent review, and a public profile that stays current.', $$[{"title":"A next action, not another empty dashboard","body":"See what is ready, what is missing, and the single most useful thing to do next.","points":["Save and resume your organization profile","Keep evidence restricted by default","Track each claim independently"]},{"title":"Compass helps you prepare","body":"AI-assisted candidates reduce repetitive typing while source references and clear uncertainty keep you in control.","points":["Accept, edit, or dismiss every suggestion","No silent publication","No legitimacy or compliance score"]},{"title":"Your public profile stays current","body":"Only the approved version of a claim appears publicly. Editing it requires a new review."}]$$::jsonb, 'PUBLISHED'),
  ('for-corporate-teams', 'For corporate and CSR teams', 'Compare causes without replacing due diligence.', 'Build shortlists from specific public indicators, current causes, contribution history, and evidence context.', $$[{"title":"Discovery with edges","body":"Search organizations and causes through explained public records rather than popularity or a black-box score."},{"title":"Shortlists for teams","body":"Save organizations, keep internal notes private, and compare current indicators before a matching commitment."}]$$::jsonb, 'PUBLISHED'),
  ('for-csr-teams', 'For CSR teams', 'Understand why a claim is trusted, not just whether it has a badge.', 'Discover organizations through specific, dated, human-reviewed indicators and keep further due diligence in your own process.', $$[{"title":"Specific indicators","body":"Registration, tax status, and other claims remain separate so each one can carry its own meaning and review date."},{"title":"A focused shortlist","body":"Save organizations for comparison without turning the trust workflow into a marketplace or automated funding decision."}]$$::jsonb, 'PUBLISHED'),
  ('how-trust-works', 'How it works', 'A visible path from private evidence to approved public facts.', 'Six understandable stages keep safety, assistance, organization ownership, independent review, and publication separate.', $$[{"title":"Upload privately","body":"A supported document enters a restricted workspace with controlled file identity and clear format rules."},{"title":"Safety check","body":"The document stays blocked until the required safety result is known."},{"title":"Read the evidence","body":"The system prepares bounded, page-aware context while keeping the underlying file restricted."},{"title":"Review suggestions","body":"Compass returns candidate facts and source references. The organization accepts, edits, or dismisses each suggestion."},{"title":"Human decision","body":"An independent reviewer compares confirmed claims with source context and records a decision."},{"title":"Publish approved facts","body":"Only approved current versions appear publicly, with meaning and review date."}]$$::jsonb, 'PUBLISHED'),
  ('trust-methodology', 'Trust methodology', 'A claim has a lifecycle, not a magic badge.', 'Understand scope, review standards, version changes, and the limits of what a public indicator can say.', $$[{"title":"Claim lifecycle","body":"Draft, confirmation, submission, review, approval, rejection, and change requests remain separate states."},{"title":"Review standards","body":"A reviewer matches a specific organization-confirmed value to permitted evidence. Approval is scoped to that claim version."},{"title":"Limitations","body":"A reviewed indicator does not certify future conduct, replace due diligence, or create a universal trust score."}]$$::jsonb, 'PUBLISHED'),
  ('compass', 'Compass', 'Assistive extraction with a person at every decision.', 'Compass can prepare candidates and source references. It cannot approve, publish, certify, or hide uncertainty.', $$[{"title":"Accept, edit, or dismiss","body":"Every candidate remains visible alongside its source context until a person decides what to submit."},{"title":"What Compass cannot do","body":"The assistant cannot determine legitimacy, fraud, funding eligibility, or publication. Malformed output fails closed."}]$$::jsonb, 'PUBLISHED'),
  ('resources', 'Resources', 'Understand the workflow before you trust the output.', 'Plain-language guides explain how evidence moves, what each indicator means, and where human judgment remains essential.', $$[{"title":"How the workflow works","body":"Follow the path from private upload through confirmation, independent review, and approved publication."},{"title":"Security and privacy","body":"See which information is public, internal, confidential, or restricted and how those boundaries remain visible."},{"title":"Help and questions","body":"Find concise answers for organizations, reviewers, donors, and CSR users."}]$$::jsonb, 'PUBLISHED'),
  ('faq', 'Frequently asked questions', 'Straight answers about evidence, AI, and review.', 'Private documents stay private, AI prepares candidates, and people remain responsible for every decision.', $$[{"title":"Does INSIPS verify an organization?","body":"No. INSIPS presents specific human-reviewed claims and their meaning. It does not provide a universal legitimacy or fraud verdict."},{"title":"Can Compass publish a claim?","body":"No. An organization must confirm it and an independent reviewer must approve the current version."},{"title":"Who can see uploaded evidence?","body":"Only appropriately authorized people in the restricted workflow. Public and CSR views receive a narrow approved projection."}]$$::jsonb, 'PUBLISHED'),
  ('security', 'Security', 'Boundaries are part of the product.', 'INSIPS is designed around tenant isolation, private evidence, safe processing, and recoverable decisions.', $$[{"title":"Deny by default","body":"Identity, role, membership, and resource state are derived on the server before protected actions are allowed."},{"title":"Safe processing","body":"Files are validated and scanned before extraction. AI candidates are schema-checked and never approve or publish claims."}]$$::jsonb, 'PUBLISHED'),
  ('help', 'Help and contact', 'Know what happened and what to do next.', 'Find a safe next step for account access, evidence preparation, contributions, volunteering, and team workflows.', $$[{"title":"A document is blocked","body":"Keep it restricted. Correct the file or account issue, then retry only the failed safe stage. Never skip a required check.","category":"Troubleshooting"},{"title":"A public indicator disappeared","body":"The underlying value may have changed. This is expected until a reviewer approves the new version.","category":"Trust workflow"},{"title":"Recover account access","body":"Use the email recovery flow when you cannot sign in. Verification codes expire, and a new code can be requested after the resend timer completes.","category":"Account and access"},{"title":"Start an organization profile","body":"Save the organization profile as you go, add evidence only when you are authorized to share it, and invite teammates after the basics are complete.","category":"Organizations"},{"title":"Make an item contribution","body":"Choose an organization need, confirm the requested quantity and condition, then follow the pickup or drop-off instructions shown in your pledge timeline.","category":"Donations and items"},{"title":"Apply for a volunteer opportunity","body":"Review the time commitment and location before applying. The organization can approve, decline, or send an instruction update from its workspace.","category":"Volunteers"},{"title":"Use discovery with your corporate team","body":"Search public organizations, save a shortlist, and keep internal notes separate from the organization’s approved public information.","category":"Corporate teams"}]$$::jsonb, 'PUBLISHED'),
  ('contact', 'Contact', 'Send the right question to the right team.', 'Use the validated contact form for support, onboarding, security, payments, or public-content questions.', $$[{"title":"Choose a topic","body":"A topic helps route the request without asking you to expose private documents or payment secrets."},{"title":"What happens next","body":"The submission receives a safe status and remains visible only to authorized support staff."}]$$::jsonb, 'PUBLISHED'),
  ('privacy', 'Privacy policy', 'Your information has a place and a boundary.', 'This product separates public, internal, confidential, and restricted information and describes how each class is handled.', $$[{"title":"Public projection","body":"Only current approved claims and permissioned public media are intended for public responses."},{"title":"Restricted workflow","body":"Evidence, extracted text, reviewer notes, tokens, and signed access URLs remain restricted."}]$$::jsonb, 'PUBLISHED'),
  ('terms', 'Terms of use', 'Use the platform with care and context.', 'These terms describe responsible use of public discovery, contribution flows, evidence workflows, and review decisions.', $$[{"title":"No universal guarantee","body":"A reviewed indicator has a defined scope and date. It is not a promise about future conduct."},{"title":"Keep access personal","body":"Do not share credentials, bypass tenant boundaries, or upload data you are not authorized to provide."}]$$::jsonb, 'PUBLISHED'),
  ('acceptable-use', 'Acceptable use', 'Keep people, evidence, and decisions safe.', 'Do not abuse public discovery, payments, media, uploads, identity, or reviewer workflows.', $$[{"title":"Do not bypass controls","body":"Attempts to evade malware scans, role boundaries, rate limits, or publication states are prohibited."},{"title":"Do not misrepresent","body":"Do not claim endorsement, verification, partnership, or impact results without documented permission and source."}]$$::jsonb, 'PUBLISHED'),
  ('cookies', 'Cookie notice', 'Use only the storage the experience needs.', 'The product should explain local theme preferences, session storage, consent-aware embeds, and necessary security controls plainly.', $$[{"title":"Necessary storage","body":"Session and security storage support authentication and safe actions."},{"title":"Preference storage","body":"Theme and local demonstration preferences can be changed from the browser."}]$$::jsonb, 'PUBLISHED'),
  ('donation-refund-policy', 'Donation and refund policy', 'Know what happens to a contribution.', 'Donation records distinguish pending, captured, failed, refunded, and transfer states.', $$[{"title":"Captured progress","body":"A cause total changes only after a verified payment event. A browser redirect alone does not increase public progress."},{"title":"Refunds and fees","body":"Refunds create compensating ledger entries. The 25-basis-point INSIPS fee remains separate from provider processing fees."}]$$::jsonb, 'PUBLISHED'),
  ('accessibility', 'Accessibility', 'The trust trail should be usable by more people.', 'INSIPS aims for WCAG 2.2 AA behavior across keyboard, touch, zoom, contrast, motion, and screen-reader use.', $$[{"title":"Every interaction has a route","body":"Carousels, sliders, feeds, dialogs, lightboxes, and drawers provide keyboard and gesture alternatives."},{"title":"Motion respects preference","body":"Reduced-motion mode removes looping movement, parallax, and unnecessary transitions."}]$$::jsonb, 'PUBLISHED'),
  ('hackathon', 'Project story', 'A product idea made tangible.', 'The local experience shows how an evidence-to-trust workflow can make public context more specific without exposing private documents.', $$[{"title":"What the product explores","body":"Preparation, confirmation, review, public discovery, contribution, and role-specific workspaces share one clear trail."},{"title":"What remains to configure","body":"Live identity providers, payments, media permissions, and cloud resources require the production setup documented for this repository."}]$$::jsonb, 'PUBLISHED')
ON CONFLICT (slug) DO UPDATE SET kicker = EXCLUDED.kicker, title = EXCLUDED.title, intro = EXCLUDED.intro, sections = EXCLUDED.sections, publishing_state = EXCLUDED.publishing_state, updated_at = now();

COMMIT;
